config/routes.rb
PhishingFramework::Application.routes.draw do

	get 'system_logs' => 'system_logs#show'

	devise_for :admins


	# image tracking routes.
	get '/reports/image/:uid.png' => 'reports#image'

	# only allow emails to be send from POST request
	post '/email/preview_email/:id' => 'email#preview', as: 'preview_email'
	post '/email/test_email/:id' =>    'email#test', as: 'test_email'
	post '/email/launch_email/:id' =>  'email#launch', as: 'launch'

	# only allow deletion from POST requests
	get '/campaigns/delete_smtp_entry/:id' => 'campaigns#list'

	get "reports/list"
	get "reports/show"
	get "reports/delete"

	get "tools/emails" => "tools#emails"
	get "tools/show_emails/:id" => "tools#show_emails", as: 'show_emails'
	post "tools/enumerate_emails" => "tools#enumerate_emails"
	delete "tools/emails/:id" => "tools#destroy_email", as: 'destroy_email'
	get "tools/download_emails/:id" => "tools#download_emails", as: "download_emails"
	get "tools/import_emails" => "tools#import_emails"

	resources :campaigns do
		collection do
			get 'options'
			get 'home'
			get 'list'
			get 'aboutus'
			get 'victims'
			get 'activity'
			delete 'destroy'
		end
		member do
			post 'clear_victims'
		end
	end

	resources :blasts, only: [:show], shallow: true

	resources :templates do
		collection do
			get 'list'
			get 'restore'
			get 'edit_email'
			get 'update_attachment'
			delete 'destroy'
		end
	end

	resources :reports do
		collection do
			get 'list'
			get 'stats'
			get 'results'
			get 'download_logs'
			get 'download_stats'
			get 'apache_logs'
			get 'smtp'
			get 'passwords'
			post 'results'
			delete 'clear'
		end
		member do
			get 'download_excel'
		end
	end

	resources :admin do
		collection do
			get 'list'
			get 'global_settings'
			put 'update_global_settings'
		end
		member do
			get 'logins'
			post 'approve'
			post 'revoke'
			delete 'destroy'
		end
	end

	resources :clones do
		member do
			get 'download'
			get 'preview'
		end
	end

	resources :tools

	root :to => 'campaigns#home'

	match 'access', :to => 'access#menu', as: 'access', via: :get

	require 'sidekiq/web'

	authenticate :admin do
		mount Sidekiq::Web => '/sidekiq'
	end

	require 'sidekiq/api'
	match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }, via: :get

	mount LetterOpenerWeb::Engine, at: 'letter_opener'

	match ':controller(/:action(/:id))(.:format)', via: [:get, :post]
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  require 'searchbing'
  require 'timeout'
  require 'open_uri_redirections'

  def emails
    # warn user if bing api key is not configured
    if GlobalSettings.first.bing_api.to_s.empty?
      flash.now[:warning] = "Bing API Key Required for Email Enumeration"
    end

    @email_searches = EmailSearch.includes(:harvested_emails).page(params[:page]).per(25).reverse_order
  end

  def show_emails
    @emails_found = EmailSearch.find(params[:id]).harvested_emails.page(params[:page]).per(100)
  end

  def destroy_email
    EmailSearch.destroy(params[:id])
    redirect_to tools_emails_path, notice: 'Email Search Destroyed'
  end

  def download_emails
    emails = String.new
    email_search = EmailSearch.find(params[:id])
    email_search.harvested_emails.each {|email| emails << "#{email.email}\n" }
    send_data(emails, :filename => "#{email_search.domain}-#{params[:id]}.txt".parameterize)
  end

  def import_emails
    campaign = Campaign.find(params[:campaign])
    email_search = EmailSearch.find(params[:search_id])
    emails = email_search.first.harvested_emails.map {|email| email.email}
    emails.each do |email| 
      newvictim = Victim.new(email_address: email)
      campaign.victims << newvictim
    end
    redirect_to victims_campaigns_path(id: campaign.id), notice: 'Emails Imported'
  end

  def enumerate_emails
    # ensure bing api key is entered
    bing_api = GlobalSettings.first.bing_api
    if bing_api.to_s.empty?
      redirect_to tools_emails_path, notice: "Unable to perform Operation without Bing API Key"
      return
    end

    # ensure domain to search has been entered
    if params[:domain].empty?
      redirect_to tools_emails_path, notice: 'Must enter a Domain'
      return
    end

    # create offset counter and urls array
    offset = 0
    urls = []
    number = (params[:crawls].to_i/50)

    # bing search to list first 50 urls and place in array
    bing_web = Bing.new(bing_api, 50, "Web")
    number.times.each do |search|
      begin
        bing_results = bing_web.search("\@#{params[:domain]}", offset)
      rescue => e
        redirect_to tools_emails_path, notice: 'Invalid Bing API Key'
        return
      end
      bing_results[0][:Web].each {|result| urls << result[:Url]}
      offset += 50
    end

    # only unique urls
    urls.uniq!

    # iterate through links and store unique emails to database
    found_emails = []
    contents = ""

    # create new search record
    email_search = EmailSearch.create(domain: params[:domain], crawls: params[:crawls].to_i)

    urls.each do |url|
      begin
        Timeout::timeout(10) {
          contents = open(url, :allow_redirections => :all).read.force_encoding("ISO-8859-1").encode("utf-8", replace: nil)
        }
      rescue
        next
      end
      emails = contents.scan(/(\w{1,20}\b(@|\[at\]|<at>|\(at\))\b#{params[:domain].gsub('.', '\.')})/)
      next if emails.empty?
      emails.each {|email| email_search.harvested_emails << HarvestedEmail.new(email: email, url: url)}
    end

    redirect_to tools_emails_path, notice: 'Email Enumeration Completed'
  end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_harvester.html.erb
<!-- Modal -->
<div class="modal fade" id="enumerateEmail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">
          <span class="glyphicon glyphicon-envelope"></span> Enumerate Email Addresses
        </h4>
      </div>
      <div class="modal-body">
        <%= form_tag(tools_enumerate_emails_path) do %>
          <%= label :domain, "Email Address Domain" %>
          <%= text_field_tag(:domain, '', autofocus: true, required: true,
              placeholder: 'Enter email address domain (e.g. domain.net)',
              class: 'form-control') %><br>
          <%= label :crawls, "Number of Links to Crawl" %>
          <%= select_tag(:crawls, options_for_select(
                [['50', 50], ['100', 100], 
                ['150', 150], ['200', 200], 
                ['250', 250], ['300', 300], 
                ['350', 350], ['400', 400], 
                ['450', 450], ['500', 500], 
                ['550', 550], ['600', 600], 
                ['650', 650], ['700', 700], 
                ['750', 750], ['800', 800], 
                ['850', 850], ['900', 900], 
                ['950', 950], ['1000', 1000]]
          ), class: 'form-control') %><br>
          <%= submit_tag "Enumerate Emails", class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/tools/_import_emails.html.erb
<!-- Modal -->
<div class="modal fade" id="importEmails-<%= search.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">
          <span class="glyphicon glyphicon-log-in"></span> Assign Addresses to Campaign
        </h4>
      </div>
      <div class="modal-body">
        <%= form_tag(tools_import_emails_path) do %>
          <%= label :campaign, "Campaign Name" %>
          <% campaigns_array = Campaign.all.map { |campaign| [campaign.name, campaign.id] } %>
          <%= select_tag :campaign, options_for_select(campaigns_array), class: 'form-control' %><br>
          <%= label :search_id, "Search ID" %>
          <%= text_field :search_id, "", value: search.id, readonly: true, class: 'form-control' %><br>
          <%= submit_tag "Import", class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/tools/emails.html.erb
<% @page_title = "Email Enumeration" %>

<div class="page-header">
  <h2>Email Enumeration</h2>
</div>

<button class="btn btn-primary" data-toggle="modal" data-target="#enumerateEmail">
  <span class="glyphicon glyphicon-search"></span> Enumerate
</button>

<% unless @email_searches.empty? %>
<div class="">
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>Domain</th>
        <th>Emails Found</th>
        <th>Links Crawled</th>
        <th class="pull-right">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @email_searches.each do |search| %>
      <tr>
        <td><%= link_to search.domain, show_emails_path(search) %></td>
        <td><%= search.harvested_emails.size %></td>
        <td><%= search.crawls %></td>
        <td>
          <div class="pull-right">
          <%= link_to "<span class='glyphicon glyphicon-new-window'></span>".html_safe, 
                "#", class: 'btn btn-xs btn-primary', 
                data: {toggle: 'modal', target: "#importEmails-#{search.id}", 
                placement: 'bottom'}, title: 'Import Emails', 
                rel: 'tooltip' %>
          <%= link_to "<span class='glyphicon glyphicon-envelope'></span>".html_safe,
                show_emails_path(search), class: 'btn btn-xs btn-default', 
                data: {toggle: 'tooltip', placement: 'bottom'}, 
                title: 'Show Emails', rel: 'tooltip' %>
          <%= link_to "<span class='glyphicon glyphicon-download-alt'></span>".html_safe,
                download_emails_path(search), class: 'btn btn-xs btn-default', 
                data: {toggle: 'tooltip', placement: 'bottom'}, 
                title: 'Download Emails', rel: 'tooltip' %>
          <%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe,
                destroy_email_path(search), method: :delete, 
                confirm: 'Are you sure you want to permanently delete this Email Search?',
                class: 'btn btn-danger btn-xs',
                data: {toggle: 'tooltip', placement: 'bottom'}, 
                title: 'Delete Emails', rel: 'tooltip' %>
          </div>
          <%= render partial: 'import_emails', locals: {search: search} %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="pull-right">
    <%= paginate @email_searches, :theme => 'twitter-bootstrap-3' %>
  </div>
</div>
<% end %>

<%= render partial: 'harvester' %>

app/views/tools/show_emails.html.erb
<% @page_title = "Harvested Emails" %>

<%= link_to '<< Back to Email Searches', tools_emails_path, class: "back-link" %>

<h2>Harvested Emails</h2>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Email</th>
      <th>Found URL</th>
    </tr>
  </thead>
  <tbody>
    <% @emails_found.each do |email| %>
    <tr>
      <td><span class='glyphicon glyphicon-globe'></span></td>
      <td><%= email.original %></td>
      <td><%= link_to truncate(email.url, length: 80), email.url, target: '_blank' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right">
  <%= paginate @emails_found, :theme => 'twitter-bootstrap-3' %>
</div>