config/routes.rb
PhishingFramework::Application.routes.draw do

	get 'system_logs' => 'system_logs#show'

	devise_for :admins


	# image tracking routes.
	get '/reports/image/:uid.png' => 'reports#image'

	# only allow emails to be send from POST request
	post '/email/preview_email/:id' => 'email#preview', as: 'preview_email'
	post '/email/test_email/:id' =>    'email#test', as: 'test_email'
	post '/email/launch_email/:id' =>  'email#launch', as: 'launch'

	# only allow deletion from POST requests
	get '/campaigns/delete_smtp_entry/:id' => 'campaigns#list'

	get "reports/list"
	get "reports/show"
	get "reports/delete"

	get "tools/emails" => "tools#emails"
	get "tools/show_emails/:id" => "tools#show_emails", as: 'show_emails'
	post "tools/enumerate_emails" => "tools#enumerate_emails"
	delete "tools/emails/:id" => "tools#destroy_email", as: 'destroy_email'
	get "tools/download_emails/:id" => "tools#download_emails", as: "download_emails"
	get "tools/import_emails" => "tools#import_emails"

	resources :campaigns do
		collection do
			get 'options'
			get 'home'
			get 'list'
			get 'aboutus'
			get 'victims'
			get 'activity'
			delete 'destroy'
		end
		member do
			post 'clear_victims'
		end
	end

	resources :blasts, only: [:show], shallow: true

	resources :templates do
		collection do
			get 'list'
			get 'restore'
			get 'edit_email'
			get 'update_attachment'
			delete 'destroy'
		end
	end

	resources :reports do
		collection do
			get 'list'
			get 'stats'
			get 'results'
			get 'download_logs'
			get 'download_stats'
			get 'apache_logs'
			get 'smtp'
			get 'passwords'
			post 'results'
			delete 'clear'
		end
		member do
			get 'download_excel'
		end
	end

	resources :admin do
		collection do
			get 'list'
			get 'global_settings'
			put 'update_global_settings'
		end
		member do
			get 'logins'
			post 'approve'
			post 'revoke'
			delete 'destroy'
		end
	end

	resources :clones do
		member do
			get 'download'
			get 'preview'
		end
	end

	resources :tools

	root :to => 'campaigns#home'

	match 'access', :to => 'access#menu', as: 'access', via: :get

	require 'sidekiq/web'

	authenticate :admin do
		mount Sidekiq::Web => '/sidekiq'
	end

	require 'sidekiq/api'
	match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }, via: :get

	mount LetterOpenerWeb::Engine, at: 'letter_opener'

	match ':controller(/:action(/:id))(.:format)', via: [:get, :post]
end

app/views/admin/delete.html.erb
<% @page_title = "Delete Admin" %>
<%= link_to("<< Back to List", {:action => 'list'}, :class => 'back-link') %>

<div class="Admin delete">
  <h2>Delete Admin</h2>
  
  <%= form_for(:admin, :url => {:action => 'destroy', :id => @admin.id}) do |f| -%>

    <p>Are you sure you want to permanently delete this Admin?</p>
    
    <table summary="Admin detail view">
      <tr>
        <th>Name</th>
        <td><%= @admin.name %></td>
      </tr>
      <tr>
        <th>Username</th>
        <td><%= @admin.username %></td>
      </tr>
      <tr>
        <th>Created</th>
        <td><%= @admin.created_at %></td>
      </tr>
      <tr>
        <th>Updated</th>
        <td><%= @admin.updated_at %></td>
      </tr>
    </table>
  
    <div class="form-buttons">
      <%= submit_tag("Delete Admin", :method => :post) %>
    </div>
    
  <% end %>
</div>

app/views/admin/global_settings.html.erb
<% @page_title = "Global Settings" %>

<%= error_messages_for(@global_settings) %>

<div class="global_settings">
  <h2>Global Settings</h2>

  <%= form_for(:global_settings, :url => {:action => 'update_global_settings'}) do |f| %>

  <table class="table borderless" summary="Global Settings fields">
    <tr>
      <th>Application Site URL</th>
      <td><span class="ui-icon ui-icon-help" title='Full Site url including HTTP(S) protocol that will be used as the base callback url for tracking phishing details from visitors'></span></td>
      <td><%= f.text_field(:site_url, placeholder: 'https://phishingfrenzy.local',
                    required: true, class: 'form-control') %></td>
    </tr>
    <tr>
    <tr>
      <th>Apache Restart Command</th>
      <td><span class="ui-icon ui-icon-help" title='Command used on the Operating System to restart Apache. This is required to manage the virtual hosts for phishing websites'></span></td>
      <td><%= f.text_field(:command_apache_restart, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Apache Status Command</th>
      <td><span class="ui-icon ui-icon-help" title='Command used on the Operating System to status Apache. This is required for monitoring the web server.'></span></td>
      <td><%= f.text_field(:command_apache_status, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Apache VHOST Command</th>
      <td><span class="ui-icon ui-icon-help" title='Command used on the Operating System for listing all Virtual Hosts.'></span></td>
      <td><%= f.text_field(:command_apache_vhosts, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Apache sites-enabled Path</th>
      <td>
        <span class="ui-icon ui-icon-help" title='Path or location of where the Apache stores the sites-enabled virtual hosts'></span></td>
      <td><%= f.text_field(:sites_enabled_path, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Reports Refresh Time</th>
      <td><span class="ui-icon ui-icon-help" title='Time in seconds use to poll the server for stats on the campaign stats page'></span></td>
      <td><%= f.text_field(:reports_refresh, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>SMTP Timeout</th>
      <td><span class="ui-icon ui-icon-help" title='Timeout in seconds to allow when sending phishing emails through the SMTP server'></span></td>
      <td><%= f.text_field(:smtp_timeout, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>BeEF URL</th>
      <td><span class="ui-icon ui-icon-help" title='URL used for BeEF to hook browsers with javascript'></span></td>
      <td><%= f.text_field(:beef_url,
                placeholder: "http://beef.phishingfrenzy.local/hook.js",
                class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Bing API Key</th>
      <td>
        <span class="ui-icon ui-icon-help" title='Bing API Key required for email enumeration'></span>
      </td>
      <td>
        <%= f.text_field(:bing_api, 
                placeholder: "BKqC2hIKr8foem2E1qiRvB5ttBQJK8objH8kZE/WJVs=", 
                class: 'form-control') %>
      </td>
    </tr>
    <tr>
      <th>Background Email</th>
      <td><span class="ui-icon ui-icon-help" title='Use Sidekiq to send emails in the background'></span></td>
      <td><%= f.check_box(:asynchronous) %></td>
    </tr>
  </table>

  <%= submit_tag("Update Changes", class: 'btn btn-primary') %>

  <% end %>

</div>

app/views/admin/list.html.erb
<% @page_title = "Admins" %>

<div class="page-header">
  <h2>Your Registration</h2>
</div>

<div class="Admin list">
  <%= link_to('Manage Account', edit_admin_registration_path(current_admin), class: 'btn btn-default') %>
  <h2>Users</h2>

  <% if params[:approved] == "false" %>
      <%= link_to "All Admins", :action => "list" %>
  <% else %>
      <%= link_to "Admins awaiting approval", :action => "list", :approved => "false" %>
  <% end %>

  <div><%= pluralize(@admins.size, 'admin') %> found</div>
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>Name</th>
        <th>Username</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= image_tag('administrator.png', size: '35x35') %></td>
        <td><%= admin.name %></td>
        <td><%= admin.username %></td>
        <td class="actions">
          <% if admin.approved? %>
              <%= link_to "Revoke", revoke_admin_path(admin), method: :post, class: 'btn btn-default btn-xs' %>
          <% else %>
              <%= link_to "Approve", approve_admin_path(admin), method: :post, class: 'btn btn-default btn-xs' %>
          <% end %>
          <%=  link_to "Logins", logins_admin_path(admin), class: 'btn btn-default btn-xs' %>
          <%= link_to "Delete", admin_path(admin), method: :delete, data: {confirm: 'Are you sure you want to permanently delete this admin?'}, class: 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/logins.html.erb
<% @page_title = "#{@admin.name} Login Archive" %>
<%= link_to("<< Back to Admins Menu", list_admin_index_path, :class => 'back-link') %>
<div class="Admin list">
  <h2><%=  @admin.name %> Logins</h2>

  <div><%= pluralize(@logins.size, 'login') %> logged out of <%= @admin.sign_in_count %> logins total </div>
  <table class="table table-striped" summary="Campaign list">
    <tr class="header">
      <th>Date</th>
      <th>IP</th>
    </tr>

    <% @logins.each do |login| %>

        <tr>
          <td><%= login.current_sign_in_at %></td>
          <td><%= login.current_sign_in_ip %></td>
        </tr>
    <% end %>
  </table>

</div>